FROM apache/superset:latest

USER root

# 1. Install pip into Superset venv
RUN /app/.venv/bin/python -m ensurepip

# 2. Upgrade pip (optional but recommended)
RUN /app/.venv/bin/python -m pip install --upgrade pip

# 3. Install Postgres driver into the SAME venv Superset uses
RUN /app/.venv/bin/python -m pip install psycopg2-binary

USER superset
